# Generated by Django 3.2.9 on 2021-11-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('pays', models.CharField(max_length=50)),
                ('cat', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('tank_id', models.IntegerField()),
            ],
        ),
    ]
